site_name: Root docs
repo_url: https://github.com/roadie-demo/react-native-sample-app
edit_uri: edit/main/docs

nav:
  - Home: index.md

plugins:
  - techdocs-core

markdown_extensions:
  - markdown_inline_mermaid
  - mkdocs_graphviz